[project]
name = "sim"
version = "0.1.0"
description = "Simulation module for motion control playground."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "componentize-py>=0.19.3",
]
